[git_branch]
symbol = 'ğŸŒ± '

[nodejs]
format = 'via [ğŸ“¦ node $version](208 bold) '

[cmd_duration]
min_time = 500
format = 'em [$duration](bold yellow)'

[character]
success_symbol = "[âœ ](green)"
error_symbol = "[âœ– ](red)"

[package]
#format = 'via [ğŸ $version](208 bold) '
format=''

[git_status]
stashed = "" 
untracked = ""

[directory]
truncation_length = 1
truncation_symbol = ""